services:
  anubis:
    image: ghcr.io/techarohq/anubis:latest
    expose:
      - "8923"
    environment:
      BIND: ":8923"
      DIFFICULTY: "5"
      METRICS_BIND: ":9090"
      SERVE_ROBOTS_TXT: "true"
      TARGET: "http://nginx"
    volumes:
      - ./anubis-config:/data/cfg
    user: "1000:1000"

  nginx:
    image: nginx
    ports:
      - "81:80"
    volumes:
      - ./www:/usr/share/nginx/html

  proxy:
    image: nginx
    ports:
      - "8923:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - anubis
